name: Deploy to Plesk (Node server)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate SSH key
        run: |
          umask 077
          cat <<'EOF' > /tmp/deploy_key
          ${{ secrets.SSH_KEY }}
          EOF
          chmod 600 /tmp/deploy_key
          ssh-keygen -lf /tmp/deploy_key

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync source (sin node_modules, .git, etc.)
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.next' \
            -e "ssh -i /tmp/deploy_key -p ${{ secrets.SSH_PORT }}" \
            ./ \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/"

      - name: Install, build & restart (remote)
        run: |
          ssh -i /tmp/deploy_key -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "set -e
             cd '${{ secrets.DEPLOY_PATH }}'
             npm ci
             npm run build
             npx pm2 startOrReload ecosystem.config.js || npx pm2 start 'npm -- start' --name soulmarket
             npx pm2 save"